### ISSUE TITLE
React-PropTypes-to-prop-types.js has a transformation error

### ISSUE THREAD

**Issue by kentcdodds** [reactjs/react-codemod#104]
When trying to upgrade to the latest version of React (migrating prop types and create class stuff), I found a LOT of errors with this particular codemod when running it on my codebase:

```
~/Developer/paypal/p2pnodeweb (pr/upgrade-react)
🚀  $ jscodeshift -t react-codemod/transforms/React-PropTypes-to-prop-types.js public/js/
Processing 691 files... 
Spawning 7 workers...
Sending 50 files to free worker...
Sending 50 files to free worker...
Sending 50 files to free worker...
Sending 50 files to free worker...
Sending 50 files to free worker...
Sending 50 files to free worker...
Sending 50 files to free worker...

...

 ERR public/js/calculator/containers/to-country/__tests__/skip-to-xoom.js Transformation error
TypeError: Cannot read property 'name' of undefined
    at /Users/kdodds/Developer/paypal/p2pnodeweb/react-codemod/transforms/React-PropTypes-to-prop-types.js:91:7
    at Array.filter (native)
    at Collection.filter (/Users/kdodds/.nvm/versions/node/v4.7.0/lib/node_modules/jscodeshift/dist/Collection.js:65:46)
    at removeDestructuredPropTypeStatements (/Users/kdodds/Developer/paypal/p2pnodeweb/react-codemod/transforms/React-PropTypes-to-prop-types.js:90:6)
    at module.exports (/Users/kdodds/Developer/paypal/p2pnodeweb/react-codemod/transforms/React-PropTypes-to-prop-types.js:163:22)

...

All done. 
Results: 
168 errors
0 unmodified
436 skipped
87 ok
```

Here's what that `__tests__/skip-to-xoom.js` file looks like:

```javascript
import React from 'react'
import { render } from 'enzyme'
import SkipToXoom from '../skip-to-xoom'

test('the rendered button redirects to the proper URL when clicked', () => {
	const toCountryData = { countryName: 'India', countryCode: 'IN' }
	const div = renderToDiv({ toCountryData, userLang: 'en_us' })
	const { attribs: { href } } = div.find('a')[0]
	expect(href).toBe('#')
})

/**
 * Render the <SkipToXoom /> component to a div with the given props
 * We have to do some fancy footwork with the Router component to get
 * the Link component in our SkipToXoom component to render out the href
 * @param {Object} props - the props to apply to the component
 * @returns {Element} - the div that contains the element
 */
function renderToDiv(props = {}) {
	return render(<SkipToXoom {...props} dispatch={() => {}} userLang="en" />)
}
```

Any ideas?

**Comment by kentcdodds** [comment]
Note that I did get errors for files that _do_ actually utilize PropTypes (like this one):

```javascript
import React, { PropTypes } from 'react'
import { StyleSheet, css } from 'aphrodite'
import * as ViewActions from '../../actions/actions'

import content from '../../lib/content'
const i18n = content('crossBorder/calc')

// Allows User to skip straight to Xoom if they want to repeat the
// prior Xoom transaction
const styles = StyleSheet.create({
	skipContainer: {
		lineHeight: '60px',
		marginBottom: 30,
		borderRadius: 5,
		backgroundColor: '#f5f7fa',
		fontSize: 15,
	},
})
const SkipToXoom = React.createClass({
	propTypes: {
		dispatch: PropTypes.func.isRequired,
		toCountryData: PropTypes.shape({
			countryName: PropTypes.string.isRequired, // localized country name
			countryCode: PropTypes.string.isRequired,
		}),
	},
	redirectToXoom() {
		this.props.dispatch(ViewActions.redirectToXoom({
			type: 'repeatUser',
			countryCode: this.props.toCountryData.countryCode,
		}))
	},
	render() {
		const { toCountryData: { countryName } } = this.props
		return (
			<div className={css(styles.skipContainer)}>
				<span className="content">
					{i18n('skipToXoom.body', { country: <strong key={countryName}>{countryName}</strong> })}
				</span>
				{' '}
				<a
					href="#"
					onClick={this.redirectToXoom}
					data-pagename="main:consumer:p2p:transfer:xb:repeatSkipToXoom"
				>
					{i18n('skipToXoom.link')}
				</a>
			</div>
		)
	},
})

export default SkipToXoom
```

**Comment by lloydh** [comment]
Yeah, I'm seeing the same error.

**Comment by ericdfields** [comment]
Still seeing this. Is it because my babel setup is in my webpack instead of babelrc?

**Comment by bvaughn** [comment]
Hey @kentcdodds! Sorry for not seeing this issue earlier. Have had my hands full the past few days.

I committed a few bug fixes this evening that should resolve the issues you reported above. (I ran the code snippets you provided to make certain.)

One thing to note: In your second example, the codemod _will_ insert semicolons after the `react` and `prop-types` imports. (Sorry!)

**Comment by kentcdodds** [comment]
> Have had my hands full the past few days.

No worries. Understandable :)

> I committed a few bug fixes this evening that should resolve the issues you reported above. (I ran the code snippets you provided to make certain.)

Great! Thanks!

> One thing to note: In your second example, the codemod will insert semicolons after the `react` and `prop-types` imports. (Sorry!)

No worries! We can autofix that away!
