### ISSUE TITLE
React-PropTypes to prop types: Transformation Error: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by notgiorgi** [reactjs/react-codemod#110]
I ran:
```sh
jscodeshift -t transforms/React-PropTypes-to-prop-types.js ../project/src/
```
It this error on almost every file:
```
 ERR ../project/src/WebAPI/application.js Transformation error
TypeError: Cannot read property 'name' of undefined
    at /home/user/react-codemod/transforms/React-PropTypes-to-prop-types.js:91:7
    at Array.filter (native)
    at Collection.filter (/home/user/.config/yarn/global/node_modules/jscodeshift/dist/Collection.js:65:46)
    at removeDestructuredPropTypeStatements (/home/user/react-codemod/transforms/React-PropTypes-to-prop-types.js:90:6)
    at module.exports (/home/gio/react-codemod/transforms/React-PropTypes-to-prop-types.js:163:22)
```

```js
// application.js
import { callApi } from './api'

export const details = ({
    ID,
    hash,
    page,
}) => callApi('application_view', {
    params: {
        id,
       hash,
       page,
    },
})

export const add = () => {}
export const search = (params) => callApi('application_search', { params })

```

results:
```
74 errors
0 unmodified
292 skipped
0 ok
Time elapsed: 1.808seconds 
```

I use babel-loader with this config:
```
['react', 'stage-1', ["env", { "targets": { "chrome": 56 }}]]
```

but as jscodeshift `--babel` flag defaults to true, I think this shouldn't be an issue.

**Comment by notgiorgi** [comment]
then I added `--extensions js,jsx`

results were
```
199 errors
0 unmodified
355 skipped
13 ok
```

same error, and only some of the files were fixed

**Comment by notgiorgi** [comment]
this is already open #104
