### ISSUE TITLE
Cannot read property 'name' of undefined, prop-types transformation

### ISSUE THREAD

**Issue by abhijeetNmishra** [reactjs/react-codemod#112]
I have many components for which prop-types transformation happening correctly, but for other components its failing with following error

```
TypeError: Cannot read property 'name' of undefined
    at /Users/z013mrq/react-codemod/transforms/React-PropTypes-to-prop-types.js:91:7
    at Array.filter (native)
    at Collection.filter (/Users/z013mrq/.nvm/versions/node/v6.9.0/lib/node_modules/jscodeshift/dist/Collection.js:65:46)
    at removeDestructuredPropTypeStatements (/Users/z013mrq/react-codemod/transforms/React-PropTypes-to-prop-types.js:90:6)
    at module.exports (/Users/z013mrq/react-codemod/transforms/React-PropTypes-to-prop-types.js:163:22)
```

One such component code example is 
```javascript
import React from 'react';
import Link from '../Link';

const Breadcrumb = ({ links }) => (
  <div itemType="http://schema.org/breadcrumb" itemProp="breadcrumb">
    ......
  </div>
);

Breadcrumb.propTypes = {
  links: React.PropTypes.arrayOf(
    React.PropTypes.shape({
      title: React.PropTypes.string.isRequired,
      href: React.PropTypes.string
    })
  ).isRequired
};

export default Breadcrumb;
```

Help!

**Comment by taylor-smith** [comment]
Check out PR #106

**Comment by bvaughn** [comment]
This has been fixed in master! Please reply here if I am incorrect. Sorry for the inconvenience.
