### ISSUE TITLE
Destructured parameters throws error in PropTypes transform 

### ISSUE THREAD

**Issue by chrisdhanaraj** [reactjs/react-codemod#126]
Hey there! 

So our codebase has a component like this

```js
import React, { PropTypes } from 'react';
import classnames from 'classnames';

const propTypes = {
  children: PropTypes.node,
  className: PropTypes.string,
};

const Accordion = ({ children, className, ...other }) => {
  const classNames = classnames('bx--accordion', className);
  return (
    <ul className={classNames} {...other}>
      {children}
    </ul>
  );
};

Accordion.propTypes = propTypes;

export default Accordion;
```

The codemod currently breaks on the destructured parameter - if I swap it over to 

```js
const Accordion = props => {
  const { children, className, ...other } = props;

  const classNames = classnames('bx--accordion', className);
  return (
    <ul className={classNames} {...other}>
      {children}
    </ul>
  );
};
```

The codemod runs perfectly fine and outputs as expected.

The error is below

```
 ERR components/Accordion.js Transformation error
TypeError: Cannot read property 'name' of undefined
    at /Users/chrisdhanaraj/bluemix/react-codemod/transforms/React-PropTypes-to-prop-types.js:103:7
    at Array.filter (native)
    at Collection.filter (/Users/chrisdhanaraj/.config/yarn/global/node_modules/jscodeshift/dist/Collection.js:65:46)
    at removeDestructuredPropTypeStatements (/Users/chrisdhanaraj/bluemix/react-codemod/transforms/React-PropTypes-to-prop-types.js:102:6)
    at module.exports (/Users/chrisdhanaraj/bluemix/react-codemod/transforms/React-PropTypes-to-prop-types.js:175:22)
```

**Comment by chrisdhanaraj** [comment]
Oh actually, looks like https://github.com/reactjs/react-codemod/pull/116 solves this issue :)

**Comment by bvaughn** [comment]
Oh, so it does. Good catch. I'll tag that PR.
