### ISSUE TITLE
Class transform fails for files with non-ASCII chars in template literals

### ISSUE THREAD

**Issue by misund** [reactjs/react-codemod#135]
Transforming a file with a template literal that contains a non-ASCII character will not work.

Any two-byte character seems to bump `rightBackTickPos` (determined by `node.loc.end`) 1 higher than what [this assert](https://github.com/benjamn/recast/blob/5bfd3f2fb9df404c1178e74516eca2bcc691ad43/lib/util.js#L274) in `recast`'s util.fixTemplateLiteral expects.

The parser seems to count the position of multibyte chars several times in a way that `recast` doesn't handle properly. At first sight the parser chosen by `jscodeshift` seems to be `babel-core`.

Example of a file that won't be transformed:
```jsx
import React from 'react';

const Foo = React.createClass({
  render() {
    return <div>{`æøåß`}</div>;
  },
});

export default Foo;
```

Output:
```
$ jscodeshift -t react-codemod/transforms/class.js ../Foo.js 
Processing 1 files... 
Spawning 1 workers...
Sending 1 files to free worker...
 ERR ../Foo.js Transformation error
AssertionError: 'd' === '`'
    at fixTemplateLiteral (/home/misund/.nvm/versions/node/v7.9.0/lib/node_modules/jscodeshift/node_modules/recast/lib/util.js:257:10)
    at Object.util.fixFaultyLocations (/home/misund/.nvm/versions/node/v7.9.0/lib/node_modules/jscodeshift/node_modules/recast/lib/util.js:167:5)
    at TreeCopier.TCp.copy (/home/misund/.nvm/versions/node/v7.9.0/lib/node_modules/jscodeshift/node_modules/recast/lib/parser.js:108:8)
    at TreeCopier.TCp.copy (/home/misund/.nvm/versions/node/v7.9.0/lib/node_modules/jscodeshift/node_modules/recast/lib/parser.js:151:24)
    at Array.map (native)
    at TreeCopier.TCp.copy (/home/misund/.nvm/versions/node/v7.9.0/lib/node_modules/jscodeshift/node_modules/recast/lib/parser.js:101:17)
    at TreeCopier.TCp.copy (/home/misund/.nvm/versions/node/v7.9.0/lib/node_modules/jscodeshift/node_modules/recast/lib/parser.js:151:24)
    at TreeCopier.TCp.copy (/home/misund/.nvm/versions/node/v7.9.0/lib/node_modules/jscodeshift/node_modules/recast/lib/parser.js:151:24)
    at Array.map (native)
    at TreeCopier.TCp.copy (/home/misund/.nvm/versions/node/v7.9.0/lib/node_modules/jscodeshift/node_modules/recast/lib/parser.js:101:17)
All done. 
Results: 
1 errors
0 unmodified
0 skipped
0 ok
Time elapsed: 1.376seconds 
```

I'm probably not going to bother to look any more at this, especially if I'm the only one having this issue.

*If you're reading this in search for a quick and dirty fix*, you can try to comment out the assert in `recast` and hope for the best. (That worked out just fine for me, but your milage may vary.)

**Comment by threepointone** [comment]
I tried this out with the latest version, and it doesn't seem to be a problem anymore. closing.
