### ISSUE TITLE
Getting error : throw new TypeError('Path must be a string. Received ' + inspect(path));

### ISSUE THREAD

**Issue by techyrajeev** [reactjs/react-codemod#167]
I am running error while react-codemod command.
I tried : ` '/Dev/web/src/'`
then 
 `/Dev/web/src/`
then
 `"/Dev/web/src/"`

With the command. But none of them worked.
Node version
$ node -v
v6.11.1

My jscodeshift version : 

```
$ jscodeshift --version
jscodeshift: 0.3.32
 - babel: 5.8.38
 - babylon: 6.17.4
 - flow: 0.52.0
 - recast: 0.12.6

```

```
$ jscodeshift -td react-codemod/transforms/React-PropTypes-to-prop-types.js '/Dev/web/src/'  
path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received true
    at assertPath (path.js:7:11)
    at Object.resolve (path.js:1146:7)
    at Object.<anonymous> (/usr/lib/node_modules/jscodeshift/bin/jscodeshift.sh:111:58)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)

```

**Comment by techyrajeev** [comment]
I was using the react-codemod path incorrectly 
Fixed it by changing the path properly.
`$ jscodeshift -t ../react-codemod/transforms/React-PropTypes-to-prop-types.js src
`
