### ISSUE TITLE
Is Node 11 broken

### ISSUE THREAD

**Issue by a-x-** [reactjs/react-codemod#218]
react-codemod/node_modules/circular-json/build/circular-json.node.js:184:1

```js
this.stringify = stringifyRecursion;
```

<details><summary>log, error, and stacktrace</summary>

```
Processing 1 files... 
Spawning 1 workers...
Sending 1 files to free worker...
[BABEL] Note: The code generator has deoptimised the styling of /Users/mxtnr/rocket/felix/frontend/projects/admin/scripts/coffee2es6jsx/react-codemod/node_modules/lodash/lodash.js as it exceeds the max of 500KB.
 ERR /Users/mxtnr/rocket/felix/frontend/projects/admin/pages/RocketBalances/Top.eslint.jsx Transformation error (Cannot set property 'stringify' of undefined)
TypeError: Cannot set property 'stringify' of undefined
    at Object.<anonymous> (/Users/mxtnr/rocket/felix/frontend/projects/admin/scripts/coffee2es6jsx/react-codemod/node_modules/circular-json/build/circular-json.node.js:184:1)
    at Module._compile (internal/modules/cjs/loader.js:734:30)
    at Module._compile (/Users/mxtnr/rocket/felix/frontend/projects/admin/node_modules/pirates/lib/index.js:83:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:745:10)
    at Object.newLoader [as .js] (/Users/mxtnr/rocket/felix/frontend/projects/admin/node_modules/pirates/lib/index.js:88:7)
    at Module.load (internal/modules/cjs/loader.js:626:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:566:12)
    at Function.Module._load (internal/modules/cjs/loader.js:558:3)
    at Module.require (internal/modules/cjs/loader.js:663:17)
    at require (internal/modules/cjs/helpers.js:20:18)
```

</details>

**Comment by a-x-** [comment]
react-codemod@4.0.0

**Comment by gormv** [comment]
Same issue here. Did you find a solution?

**Comment by a-x-** [comment]
I postponed it...

**Comment by jpolo** [comment]
I can reproduce in node v8.11.3 so definitely not a v11 problem

**Comment by threepointone** [comment]
Is this still an issue? Can you make a git repo that shows this problem?

**Comment by threepointone** [comment]
I’m going to close this, happy to reopen if someone shares a reproducing example.
