### ISSUE TITLE
"Unknown encoding" error

### ISSUE THREAD

**Issue by benwalsh** [reactjs/react-codemod#36]
I've tried saving my files in various encodings both in Sublime Text and by converting using `iconv` but I get encoding errors every time:

MacOS 10.11.3, node 5.7.0, npm 3.6.0

```
jscodeshift path/to/my/file.jsx -v 2 -t ~/react-codemod/transforms/sort-comp.js 
Processing 1 files... 
Spawning 1 workers...
Sending 1 files to free worker...
buffer.js:638
          throw new TypeError('Unknown encoding: ' + encoding);
          ^
TypeError: Unknown encoding: path/to/my/file.jsx
    at Buffer.write (buffer.js:638:17)
    at fromString (buffer.js:113:26)
    at new Buffer (buffer.js:58:12)
    at createWriteReq (net.js:723:38)
    at WriteStream.Socket._writeGeneric (net.js:675:11)
    at WriteStream.Socket._write (net.js:698:8)
    at doWrite (_stream_writable.js:301:12)
    at writeOrBuffer (_stream_writable.js:287:5)
    at WriteStream.Writable.write (_stream_writable.js:215:11)
    at WriteStream.Socket.write (net.js:624:40)
```

**Comment by cpojer** [comment]
This is most likely not an issue with react-codemod and definitely out of the scope of this project. react-codemod is also one of our self-service repositories, we don't really fix community issues but we are happy to take Pull Requests.

I'm gonna cc @fkling just in case he has seen this before around jscodeshift, although I doubt it is related to jscodeshift.
