### ISSUE TITLE
 sort-comp is not working

### ISSUE THREAD

**Issue by ondrejsevcik** [reactjs/react-codemod#51]
Hi, when I run `sort-comp` transformation, it throws following error:
```
Error: Cannot read config package: eslint-config-airbnb
Error: Cannot find module 'eslint-config-airbnb'
Referenced from: C:\projects\client\.eslintrc
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at loadPackage (C:\projects\react-codemod\node_modules\eslint\lib\config\config-file.js:168:16)
    at loadConfigFile (C:\projects\react-codemod\node_modules\eslint\lib\config\config-file.js:212:1
8)
    at load (C:\projects\react-codemod\node_modules\eslint\lib\config\config-file.js:385:18)
    at C:\projects\react-codemod\node_modules\eslint\lib\config\config-file.js:326:36
    at Array.reduceRight (native)
    at applyExtends (C:\projects\react-codemod\node_modules\eslint\lib\config\config-file.js:309:28)
```

I've run `npm install` within `react-codemod` directory but it didn't help.

**Comment by cpojer** [comment]
cc @turadg

**Comment by cpojer** [comment]
fixed on master!

**Comment by reergymerej** [comment]
[getConfigForFile][1] isn't finding the airbnb plugin.  I've replicated with globally and locally installed [airbnb config]s[2].  I added a try...catch around it, but we should probably figure out the scope of this.  Is it just this plugin, only when extending, etc?

[1]: http://eslint.org/docs/developer-guide/nodejs-api#getconfigforfile
[2]: https://www.npmjs.com/package/eslint-config-airbnb

**Comment by cpojer** [comment]
It's probably some npm module that has an eslintrc shipped with it but is installed as a regular dependency so its dev dependencies aren't there. You should probably not run codemods on node_modules folders, but it doesn't hurt to silently ignore this.

**Comment by reergymerej** [comment]
Looks like this is an [ESLint issue](https://github.com/eslint/eslint/issues/6315).

**Comment by ondrejsevcik** [comment]
Thank you guys for such a quick fix :+1:
