### ISSUE TITLE
pure-render-mixin transformation error

### ISSUE THREAD

**Issue by eschaefer** [reactjs/react-codemod#7]
Getting error:
```
ERR  ./app/node_modules/components/tweet/index.jsx Transformation error
TypeError: Cannot read property 'get' of undefined
    at Collection.get (/Users/eschaefer/.nvm/versions/node/v4.2.1/lib/node_modules/jscodeshift/dist/Collection.js:205:18)
    at deletePureRenderMixin (/Users/eschaefer/Projects/react-codemod/transforms/pure-render-mixin.js:159:54)
    at removePureRenderMixin (/Users/eschaefer/Projects/react-codemod/transforms/pure-render-mixin.js:180:7)
```

when running the `pure-render-mixin.js` on example component:

```
import React from 'react';
import TranslationsMixin from 'mixins/translations';

var Tweet = React.createClass({

  mixins: [TranslationsMixin],

  render() {

    return (
      <div>
        Stuff
      </div>
    );
  }
});

export default Tweet;
```

I have tried passing the `--mixin-name=TranslationsMixin` flag, but no luck. Any idea what could be the issue?

**Comment by eschaefer** [comment]
Ah nevermind, this is because of the ES6 `import`s. It works if the mixin is `require`d. Might just do some mass find-and-replacing before running this on the rest of my components.
